require('dotenv').config();
const { Client, GatewayIntentBits, Collection, ActionRowBuilder, StringSelectMenuBuilder, StringSelectMenuOptionBuilder, ModalBuilder, TextInputBuilder, TextInputStyle, Events, EmbedBuilder } = require('discord.js');
const fs = require('fs'); const path = require('path'); const express = require('express');
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildPresences] });
client.commands = new Collection(); const commandsPath = path.join(__dirname,'commands'); if(!fs.existsSync(commandsPath))fs.mkdirSync(commandsPath); for(const file of fs.readdirSync(commandsPath).filter(f=>f.endsWith('.js'))){const cmd=require(path.join(commandsPath,file));if(cmd.name&&cmd.execute)client.commands.set(cmd.name,cmd);}
const TEAM_ROLE_ID='1439948657670754324', DEV_ROLE_ID='1442556761541447720'; const DISCORD_GUILD_ID='1417557162875555974'; const badWords=['חרא','מניאק','זונה','בן זונה','דפוק','מטומטם','מפגר']; const warnings=new Map();
client.once('ready',()=>{console.log(`✅ Logged in as ${client.user.tag}`);client.user.setActivity('EddyWEB | Discord');});
client.on('messageCreate',async message=>{if(message.author.bot||!message.content.startsWith('!'))return;const args=message.content.slice(1).trim().split(/\s+/),name=args.shift().toLowerCase(),command=client.commands.get(name);if(!command)return;try{await command.execute(message,args,client);}catch(err){console.error('Command error:',err);message.reply('❌ שגיאה בהרצת הפקודה.');}});
client.on('messageCreate',async message=>{if(message.author.bot||!message.guild)return;const found=badWords.some(w=>message.content.toLowerCase().includes(w));if(!found)return;const userId=message.author.id;let c=(warnings.get(userId)||0)+1;warnings.set(userId,c);await message.reply(`⚠️ שפה לא מתאימה (${c}/3).`);});
const PORT=process.env.PORT||3000; const app=express(); app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');next();}); app.get('/',(req,res)=>res.send('Eddy Bot is online!')); app.get('/health',(req,res)=>res.status(200).send('OK'));
app.get('/api/discord',(req,res)=>{const guild=client.guilds.cache.get(DISCORD_GUILD_ID);if(!guild)return res.status(503).json({ok:false,error:'Eddy Discord server not found or bot not ready',guildId:DISCORD_GUILD_ID,availableGuilds:client.guilds.cache.map(g=>({id:g.id,name:g.name}))});res.json({ok:true,guildId:guild.id,name:guild.name,members:guild.memberCount,humans:guild.members.cache.filter(m=>!m.user.bot).size,bots:guild.members.cache.filter(m=>m.user.bot).size,online:guild.presences.cache.filter(p=>!p.user?.bot).size});});
app.listen(PORT,'0.0.0.0',()=>console.log(`🌐 Web server running on port ${PORT}`)); client.login(process.env.TOKEN);