require('dotenv').config();
const { Client, GatewayIntentBits, Collection } = require('discord.js');
const fs=require('fs'),path=require('path'),express=require('express');
const { installGroqDiscordBridge } = require('./integrations/groq-discord');
const { installPanelAdmin, loadPanelConfig } = require('./panel-admin');
const installInviteTracker = require('./services/invite-tracker');
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildPresences]});
client.commands=new Collection();const commandsPath=path.join(__dirname,'commands');if(!fs.existsSync(commandsPath))fs.mkdirSync(commandsPath);for(const file of fs.readdirSync(commandsPath).filter(f=>f.endsWith('.js'))){const cmd=require(path.join(commandsPath,file));if(cmd.name&&cmd.execute)client.commands.set(cmd.name,cmd);}
installInviteTracker(client);
const DISCORD_GUILD_ID='1417557162875555974';let panelConfig=loadPanelConfig();let STAFF_ROLE_IDS=panelConfig.roles;const OLD_TICKETS_CHANNEL_ID='1492042358462615562';const SAVED_CHATS_CATEGORY_ID='1541363285490663455';const DATA_DIR=path.join(__dirname,'data');const KNOWLEDGE_FILE=path.join(DATA_DIR,'groq-staff-knowledge.json');const MEMORY_FILE=path.join(DATA_DIR,'groq-tickets.json');
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}}
function panelAuthorized(req){const password=process.env.PANEL_PASSWORD;return !!password&&req.get('x-panel-password')===password;}
function requirePanel(req,res,next){if(!panelAuthorized(req))return res.status(401).json({ok:false,error:'Panel password required'});next();}
client.once('ready',()=>{console.log(`Logged in as ${client.user.tag}`);client.user.setActivity('EddyWEB | Discord');});
client.on('guildMemberAdd',async member=>{if(member.guild.id!==DISCORD_GUILD_ID||member.user.bot)return;const commandList=[...client.commands.values()].slice(0,15).map(command=>`• !${command.name} — ${command.description||'פקודה זמינה'}`).join('\n');const welcome=`👋 **ברוכים הבאים לשרת Eddy!**\n\nהיי ${member.user.username}! שמחים שהצטרפת אלינו 🎉\n\n🎮 **מה אפשר לעשות כאן?**\n• לשחק ולהתחבר עם חברים\n• לקבל עזרה ותמיכה מהצוות\n• לפתוח טיקט כשצריך עזרה\n• להשתמש בפקודות של הבוט\n• להתעדכן באירועים, עדכונים והודעות חשובות\n\n📚 **עזרה ופקודות**\n${commandList||'• !help — הצגת רשימת הפקודות הזמינות'}\n\n💡 **צריך עזרה?**\nאפשר להשתמש ב-!help כדי לראות את הפקודות, או לפתוח טיקט בערוץ המתאים בשרת.\n\n✨ מקווים שתיהנו בשרת ותכירו חברים חדשים!\n\n— צוות Eddy`;try{await member.send(welcome);console.log(`Welcome DM sent to ${member.user.tag}`);}catch(error){console.log(`Could not send welcome DM to ${member.user.tag}: ${error?.message||error}`);}});
client.on('messageCreate',async message=>{if(message.author.bot||!message.content.startsWith('!'))return;const args=message.content.slice(1).trim().split(/\s+/),name=args.shift().toLowerCase(),command=client.commands.get(name);if(!command)return;panelConfig=loadPanelConfig();const rule=panelConfig.commands[name];if(rule?.enabled===false)return;if(rule?.roleId&&!message.member?.roles.cache.has(rule.roleId))return;try{await command.execute(message,args,client);}catch(err){console.error('Command error:',err);message.reply('שגיאה בהרצת הפקודה.').catch(()=>{});}});
installGroqDiscordBridge(client);const PORT=process.env.PORT||3000;const app=express();app.use(express.json({limit:'100kb'}));app.use(express.static(path.join(__dirname,'public')));app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Panel-Password');next();});
const transcriptStore=new Map();const TRANSCRIPT_TTL=24*60*60*1000;
app.get('/transcript/:id',(req,res)=>{const item=transcriptStore.get(req.params.id);if(!item||item.expiresAt<Date.now()){transcriptStore.delete(req.params.id);return res.status(404).send('<!doctype html><html lang="he" dir="rtl"><meta charset="utf-8"><title>Transcript expired</title><body style="font-family:Arial;text-align:center;padding:60px"><h1>⏳ הקישור פג</h1><p>קישור ה־Transcript אינו זמין יותר.</p></body></html>');}res.set('Content-Type','text/html; charset=utf-8');res.set('Cache-Control','no-store');res.send(item.html);});
function saveTranscript(html){const id=require('crypto').randomBytes(18).toString('hex');transcriptStore.set(id,{html,expiresAt:Date.now()+TRANSCRIPT_TTL});return id;}
setInterval(()=>{const now=Date.now();for(const [id,item] of transcriptStore){if(item.expiresAt<now)transcriptStore.delete(id);}},60*60*1000).unref();
function servePanel(req,res){const file=path.join(__dirname,'public','panel.html');let html=fs.readFileSync(file,'utf8');if(!html.includes('panel-admin-ui.js'))html=html.replace('</body>','<script src="/panel-admin-ui.js"></script></body>');res.type('html').send(html)}
app.get('/',servePanel);app.get('/panel',servePanel);app.get('/health',(req,res)=>res.status(200).send('OK'));
app.get('/api/discord',(req,res)=>{const guild=client.guilds.cache.get(DISCORD_GUILD_ID);if(!guild)return res.status(503).json({ok:false,error:'Eddy Discord server not found or bot not ready'});const roleData={};let totalAvailable=0;for(const [name,id] of Object.entries(STAFF_ROLE_IDS)){const role=guild.roles.cache.get(id);const members=role?role.members.filter(m=>!m.user.bot):new Map();const online=members.filter(m=>m.presence?.status&&m.presence.status!=='offline').size;roleData[name]={roleId:id,name:role?.name||name,total:members.size,online,available:online};totalAvailable+=online;}const humans=guild.members.cache.filter(m=>!m.user.bot).size;const bots=guild.members.cache.filter(m=>m.user.bot).size;res.json({ok:true,guildId:guild.id,name:guild.name,members:guild.memberCount,humans,bots,online:guild.presences.cache.filter(p=>!p.user?.bot).size,staff:{totalAvailable,roles:roleData}});});
app.post('/api/panel/login',(req,res)=>{const supplied=String(req.body?.password||'');const expected=process.env.PANEL_PASSWORD;if(!expected)return res.status(503).json({ok:false,error:'PANEL_PASSWORD is not configured on Render'});if(supplied!==expected)return res.status(401).json({ok:false,error:'Invalid password'});res.json({ok:true});});
app.get('/api/panel/settings',requirePanel,(req,res)=>{const guild=client.guilds.cache.get(DISCORD_GUILD_ID);const memory=readJson(MEMORY_FILE,{});const knowledge=readJson(KNOWLEDGE_FILE,{});const setting=(name,secret=false)=>({name,configured:!!process.env[name],value:secret?(process.env[name]?'••••••••':''):String(process.env[name]||'')});const settings=[setting('GROQ_API_KEY',true),setting('GROQ_MODEL'),setting('GROQ_MAX_TOKENS'),setting('GROQ_SYSTEM_PROMPT'),setting('PANEL_PASSWORD',true),{name:'DISCORD_TOKEN',configured:!!process.env.TOKEN,value:process.env.TOKEN?'••••••••':''},{name:'DISCORD_GUILD_ID',configured:true,value:DISCORD_GUILD_ID},{name:'OLD_TICKETS_CHANNEL_ID',configured:true,value:OLD_TICKETS_CHANNEL_ID},{name:'SAVED_CHATS_CATEGORY_ID',configured:true,value:SAVED_CHATS_CATEGORY_ID},{name:'PORT',configured:!!process.env.PORT,value:String(process.env.PORT||3000)}];const knowledgeCount=Object.values(knowledge).reduce((n,x)=>n+(Array.isArray(x)?x.length:0),0);res.json({ok:true,settings,commands:client.commands.map(c=>({name:c.name,description:c.description||'',enabled:panelConfig.commands[c.name]?.enabled!==false,roleId:panelConfig.commands[c.name]?.roleId||null})),roles:STAFF_ROLE_IDS,bot:{tag:client.user?.tag||null,userId:client.user?.id||null,uptime:client.uptime||0},guild:{id:guild?.id||DISCORD_GUILD_ID,name:guild?.name||null},storage:{tickets:Object.keys(memory).length,learnedStaffFacts:knowledgeCount}});});
app.get('/api/panel/knowledge',requirePanel,(req,res)=>{const knowledge=readJson(KNOWLEDGE_FILE,{});const items=Array.isArray(knowledge[DISCORD_GUILD_ID])?knowledge[DISCORD_GUILD_ID]:[];res.json({ok:true,count:items.length,items:items.slice().reverse().slice(0,500)});});
async function readChannelMessages(channel,limit=100){const all=[];let before;try{while(all.length<limit){const batch=await channel.messages.fetch({limit:Math.min(100,limit-all.length),before});if(!batch.size)break;all.push(...batch.values());before=batch.last()?.id;if(batch.size<100)break;}}catch(error){return {messages:all,error:error?.message||'permission denied'};}return {messages:all,error:null};}
function serializeMessages(messages){return messages.sort((a,b)=>a.createdTimestamp-b.createdTimestamp).map(m=>{const buttons=[];for(const row of (m.components||[])){for(const component of (row.components||[])){if(component.type===2)buttons.push({label:component.label||'Button',style:component.style||2,url:component.url||null,customId:component.customId||null,disabled:!!component.disabled});}}let content=m.content||'';if(buttons.length)content+=(content?'\n':'')+'כפתורים: '+buttons.map(b=>b.url?`${b.label} → ${b.url}`:b.label).join(' | ');return {id:m.id,author:m.author?.tag||m.author?.username||'unknown',authorId:m.author?.id||null,content,createdAt:new Date(m.createdTimestamp).toISOString(),bot:!!m.author?.bot,attachments:m.attachments?.size||0,buttons};});}
app.get('/api/panel/tickets',requirePanel,async(req,res)=>{const guild=client.guilds.cache.get(DISCORD_GUILD_ID);if(!guild)return res.status(503).json({ok:false,error:'Guild unavailable'});const memory=readJson(MEMORY_FILE,{});const tickets=[];for(const channel of guild.channels.cache.values()){if(!channel.isTextBased?.()||typeof channel.name!=='string'||!channel.name.toLowerCase().startsWith('ticket'))continue;const result=await readChannelMessages(channel,100);const mem=memory[channel.id]||{};tickets.push({id:channel.id,name:channel.name,category:channel.parent?.name||null,source:'open-ticket',sourceLabel:'טיקט',createdAt:mem.createdAt||channel.createdAt?.toISOString()||null,openerId:mem.openerId||null,openerName:mem.openerName||null,staffActive:!!mem.staffActive,messages:serializeMessages(result.messages),readError:result.error});}const oldChannel=guild.channels.cache.get(OLD_TICKETS_CHANNEL_ID);if(oldChannel?.isTextBased?.()){const result=await readChannelMessages(oldChannel,2000);tickets.push({id:oldChannel.id,name:oldChannel.name||'Old Tickets',category:oldChannel.parent?.name||null,source:'old-tickets',sourceLabel:'טיקטים ישנים',createdAt:oldChannel.createdAt?.toISOString()||null,openerId:null,openerName:null,staffActive:false,messages:serializeMessages(result.messages),readError:result.error});}const category=guild.channels.cache.get(SAVED_CHATS_CATEGORY_ID);if(category?.type===4){for(const channel of guild.channels.cache.values()){if(channel.parentId!==SAVED_CHATS_CATEGORY_ID||!channel.isTextBased?.())continue;const result=await readChannelMessages(channel,500);tickets.push({id:channel.id,name:channel.name||'saved-chat',category:category.name||'Saved Chats',source:'saved-chat',sourceLabel:'צ׳אט שמור',createdAt:channel.createdAt?.toISOString()||null,openerId:null,openerName:null,staffActive:false,messages:serializeMessages(result.messages),readError:result.error});}}res.json({ok:true,count:tickets.length,tickets});});
installPanelAdmin(app,client,requirePanel,[...client.commands.values()]);app.listen(PORT,'0.0.0.0',()=>console.log(`Web server running on port ${PORT}`));client.login(process.env.TOKEN);