// EddyBot Panel administration helpers.
const fs=require('fs'),path=require('path');
const CONFIG_FILE=path.join(__dirname,'data','panel-config.json');
const DEFAULT_CONFIG={roles:{team:'1439948657670754324',developers:'1442556761541447720',helpers:'1531588090588823614',moderators:'1439948877183582208'},commands:{}};
function loadPanelConfig(){try{const saved=JSON.parse(fs.readFileSync(CONFIG_FILE,'utf8'));return {...DEFAULT_CONFIG,...saved,roles:{...DEFAULT_CONFIG.roles,...(saved.roles||{})},commands:saved.commands||{}}}catch{return JSON.parse(JSON.stringify(DEFAULT_CONFIG))}}
function savePanelConfig(config){fs.mkdirSync(path.dirname(CONFIG_FILE),{recursive:true});fs.writeFileSync(CONFIG_FILE,JSON.stringify(config,null,2))}
function validSnowflake(id){return /^\d{17,20}$/.test(String(id||''))}
function installPanelAdmin(app,client,requirePanel,commands){
 const getGuild=()=>client.guilds.cache.get(process.env.DISCORD_GUILD_ID||'1417557162875555974');
 app.get('/api/panel/admin',requirePanel,(req,res)=>{const config=loadPanelConfig(),guild=getGuild();if(!guild)return res.status(503).json({ok:false,error:'Guild unavailable'});const configured=new Map(Object.entries(config.roles).map(([k,id])=>[String(id),k]));const roles=[...guild.roles.cache.values()].filter(r=>r.id!==guild.id).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,color:r.hexColor,position:r.position,members:r.members.size,manageable:r.editable,mentionable:r.mentionable,hoist:r.hoist,managed:r.managed,configuredKeys:configured.has(r.id)?[configured.get(r.id)]:[]}));res.json({ok:true,guild:{id:guild.id,name:guild.name,roleCount:roles.length},roles,configuredRoles:Object.entries(config.roles).map(([key,id])=>({key,id,name:guild.roles.cache.get(id)?.name||key,exists:guild.roles.cache.has(id)})),commands:commands.map(c=>({name:c.name,description:c.description||'',enabled:config.commands[c.name]?.enabled!==false,roleId:config.commands[c.name]?.roleId||null}))})});
 app.post('/api/panel/admin/role',requirePanel,(req,res)=>{const{key,id}=req.body||{};if(!key||!validSnowflake(id))return res.status(400).json({ok:false,error:'Invalid role ID'});const guild=getGuild(),role=guild?.roles.cache.get(String(id));if(!role)return res.status(404).json({ok:false,error:'Role not found in this server'});const config=loadPanelConfig();config.roles[key]=String(id);savePanelConfig(config);res.json({ok:true,saved:true,role:{id:role.id,name:role.name}})});
 app.post('/api/panel/admin/role/create',requirePanel,async(req,res)=>{const{key,name,color}=req.body||{};if(!key||!name)return res.status(400).json({ok:false,error:'Role name is required'});const guild=getGuild();if(!guild)return res.status(503).json({ok:false,error:'Guild unavailable'});try{const role=await guild.roles.create({name:String(name).slice(0,100),color:color||undefined,reason:'Created from EddyBot Panel'});const config=loadPanelConfig();config.roles[key]=role.id;savePanelConfig(config);res.json({ok:true,role:{id:role.id,name:role.name}})}catch(e){res.status(500).json({ok:false,error:e.message})}});
 app.post('/api/panel/admin/command',requirePanel,(req,res)=>{const{name,enabled,roleId}=req.body||{};if(!name||(roleId&&!validSnowflake(roleId)))return res.status(400).json({ok:false,error:'Invalid command or role ID'});const config=loadPanelConfig();config.commands[name]={enabled:enabled!==false,roleId:roleId||null};savePanelConfig(config);res.json({ok:true,command:config.commands[name]})});
}
module.exports={installPanelAdmin,loadPanelConfig};
